# Generated by Django 3.0.5 on 2020-06-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models.profiles


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name company', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Position inside a company', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('indefinido', 'Indefinido')], default='indefinido', help_text='Genere of user', max_length=20)),
                ('picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=users.models.profiles.remove_image_old)),
                ('type_user', models.CharField(choices=[('programmer', 'Programmer'), ('administrador', 'Administrador')], default='programmer', help_text='User rank', max_length=15)),
                ('url_account_github', models.CharField(blank=True, max_length=200, null=True)),
                ('url_account_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('years_development', models.IntegerField(default=0, help_text='Years of development experience')),
                ('years_configuration', models.IntegerField(default=0, help_text='Years of configuration experience')),
                ('years_integration', models.IntegerField(default=0, help_text='Years of integration experience')),
                ('years_requirements', models.IntegerField(default=0, help_text='Years of requirements experience')),
                ('years_design', models.IntegerField(default=0, help_text='Years of design experience')),
                ('years_tests', models.IntegerField(default=0, help_text='Years of testing experience')),
                ('years_support', models.IntegerField(default=0, help_text='Years of support experience')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='User profile creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='User profile update date')),
                ('experience_languages', models.ManyToManyField(related_name='experience_languages', to='programs.ProgrammingLanguage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='message of notification', max_length=60)),
                ('was_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_position', models.IntegerField(default=0, help_text='Years occupying the position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_experience', to='users.Company')),
                ('position_company', models.ForeignKey(help_text='User position within a company', on_delete=django.db.models.deletion.CASCADE, related_name='position_company', to='users.PositionCompany')),
                ('user', models.ForeignKey(help_text='User experencie', on_delete=django.db.models.deletion.CASCADE, related_name='experencies_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
