# Generated by Django 3.0.5 on 2020-06-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterField(
            model_name='experiencecompany',
            name='name_company',
            field=models.CharField(help_text='Name company', max_length=70),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
