# Generated by Django 3.0.5 on 2020-06-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200613_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url_account_github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url_account_linkedin',
        ),
    ]
