# Generated by Django 3.0.5 on 2020-06-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=100)),
                ('description', models.CharField(max_length=250, validators=[projects.validators.validate_min_length_description])),
                ('status', models.CharField(choices=[('En proceso', 'Procesando'), ('Cancelado', 'Cancelado'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado')], default='En proceso', help_text='This atributte allows to save the project status', max_length=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('planning_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_project', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='project_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Module name', max_length=100)),
                ('description', models.CharField(help_text='Module description', max_length=200, validators=[projects.validators.validate_min_length_description])),
                ('planning_date', models.DateField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='projects.Project')),
            ],
        ),
    ]
