# Generated by Django 3.0.5 on 2020-06-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_of_code', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name', max_length=100)),
                ('description', models.CharField(max_length=200, validators=[projects.validators.validate_min_length_description])),
                ('planning_date', models.DateField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('name', models.CharField(help_text='Programming language name', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(help_text='Programming language image', upload_to='languages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeEstimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReusedPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_lines', models.IntegerField(default=0)),
                ('current_lines', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_reused_part', to='programs.Program')),
                ('program_reused_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reused_part', to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report name', max_length=100)),
                ('date', models.DateTimeField()),
                ('objetive', models.TextField(max_length=350)),
                ('description', models.TextField(max_length=350)),
                ('conditions', models.TextField(max_length=350)),
                ('expect_results', models.TextField(max_length=350)),
                ('current_results', models.TextField(blank=True, max_length=350, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_view', to='programs.Program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_language', to='programs.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='program',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_module', to='projects.Module'),
        ),
        migrations.AddField(
            model_name='program',
            name='programmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NewPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('planning_methods', models.IntegerField()),
                ('planning_lines', models.IntegerField()),
                ('current_methods', models.IntegerField(default=0)),
                ('current_lines', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_part', to='programs.Estimation')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_part_program', to='programs.Program')),
            ],
        ),
        migrations.AddField(
            model_name='estimation',
            name='size_estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_estimation_proxy', to='programs.SizeEstimation'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='type_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_proxy', to='programs.TypePart'),
        ),
        migrations.CreateModel(
            name='BasePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_planned_base', models.IntegerField(default=0)),
                ('lines_planned_deleted', models.IntegerField(default=0)),
                ('lines_planned_edited', models.IntegerField(default=0)),
                ('lines_planned_added', models.IntegerField(default=0)),
                ('lines_current_base', models.IntegerField(default=0)),
                ('lines_current_deleted', models.IntegerField(default=0)),
                ('lines_current_edited', models.IntegerField(default=0)),
                ('lines_current_added', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_base_part', to='programs.Program')),
                ('program_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_part', to='programs.Program')),
            ],
        ),
    ]
