# Generated by Django 3.0.5 on 2020-06-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pip name', max_length=100)),
                ('date', models.DateTimeField()),
                ('problems', models.TextField(max_length=350)),
                ('proposal', models.TextField(max_length=350)),
                ('comment', models.TextField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_pip_program', to='programs.Program')),
            ],
        ),
    ]
