# Generated by Django 3.0.5 on 2020-06-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_pip'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='total_lines',
            field=models.IntegerField(default=0),
        ),
    ]
