# Generated by Django 3.0.5 on 2020-07-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200708_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='total_lines',
        ),
    ]
