# Generated by Django 3.0.5 on 2020-07-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_remove_program_total_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='total_lines',
            field=models.IntegerField(default=0),
        ),
    ]
