# Generated by Django 3.0.5 on 2020-06-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
