# Generated by Django 3.0.5 on 2020-06-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_phase_order_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='order_index',
            field=models.IntegerField(unique=True),
        ),
    ]
