# Generated by Django 3.0.5 on 2020-07-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200621_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['phase__order_index']},
        ),
    ]
